/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java")
    id("xyz.jpenilla.run-velocity") version "2.3.1"
}

group = "uk.co.nikodem"
version = "1.0"
description = "DFProxyPlugin"

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.opencollab.dev/main/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.viaversion.com/")
    }
}

dependencies {
    implementation("com.google.code.gson:gson:2.13.2")
    implementation("org.geysermc.geyser:api:2.9.0-SNAPSHOT")
    implementation("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")
    implementation("com.viaversion:viaversion:5.5.2-SNAPSHOT")
    implementation("com.viaversion:viaversion-velocity:5.5.2-SNAPSHOT")
    implementation("com.viaversion:viaversion-api:5.5.2-SNAPSHOT")
    implementation("team.unnamed:creative-server:1.7.3")
    implementation("net.dv8tion:JDA:6.2.0")
    implementation("club.minnced:discord-webhooks:0.8.4")

    annotationProcessor("com.velocitypowered:velocity-api:3.4.0-SNAPSHOT")
}

tasks {
    runVelocity {
        // Configure the Velocity version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        velocityVersion("3.4.0-SNAPSHOT")
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}